language: node_js

branches:
  only:
    - gh-pages

env:
  global:
    - URL="https://w3c.github.io/mediacapture-record/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html"
    - secure: "W735tVaiK8I/zcfuD/QwdfqbIdgu0upt5V9YX/SDOpjuTMFUNtKE40qjtViclV6Vyh+oVR5JoWTenlTOrWkImfNudFfJYx3AvzmwYKlC+DOjHFDbEDVo3v0uiQEdPVqgTVs9JHHY/CsLE6YBgATib4NIopMXYJ+UzrSzCPM8twk="
 
script:
  - echo "ok"

after_success:
  - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
