name: Auto-publish
on:
  pull_request: {}
  push:
    paths:
      - MediaRecorder.bs
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: MediaRecorder.bs
          # Please use the URL that's appropriate for your working group!
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          VALIDATE_LINKS: false
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_NOTIFICATIONS_CC: dom@w3.org
          W3C_BUILD_OVERRIDE: |
            shortname: mediastream-recording
            status: WD
            
